models/User.php
<?php
namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\mongodb\ActiveRecord;
use MongoDB\BSON\ObjectId;

class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 10;

    public static $arrStatus = array(
        self::STATUS_INACTIVE => 'ไม่ใช้งาน',
        self::STATUS_ACTIVE => 'ใช้งาน',
    );

	/**
	 * @return array list of attribute names.
	 */
	public function attributes()
	{
		return ['_id', 'id', 'username', 'name', 'status', 'createTime', 'role', 'organization', 'serverIP', 'officeIP', 'auth_key', 'password_hash', 'activeSession'];
	}


	/**
	 * {@inheritdoc}
	 */
	public static function findIdentity($id)
	{
        try {
    		$identity = static::findOne(['username' => $id, 'status' => self::STATUS_ACTIVE]);
    	}
    	catch(\Exception $ex) {
    		$identity = null;
    	}

        return $identity;
	}

	/**
	 * {@inheritdoc}
	 */
	public static function findIdentityByAccessToken($token, $type = null)
	{
		throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
	}

	/**
	 * Finds user by username
	 *
	 * @param string $username
	 * @return static|null
	 */
	public static function findByUsername($username)
	{
		return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
	}

	/**
	 * {@inheritdoc}
	 */
	public function getId()
	{
		return (string)$this->username;
	}

	/**
	 * {@inheritdoc}
	 */
	public function getAuthKey()
	{
		return $this->auth_key;
	}

	/**
	 * {@inheritdoc}
	 */
	public function validateAuthKey($authKey)
	{
		return $this->authKey === $authKey;
	}

	/**
	 * Validates password
	 *
	 * @param string $password password to validate
	 * @return bool if password provided is valid for current user
	 */
	public function validatePassword($password)
	{
		return Yii::$app->security->validatePassword($password, $this->password_hash);
    }
    
    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

controllers/UserController.php
<?php
namespace app\controllers;

use \Yii;
use MongoDB\BSON\ObjectID;
use MongoDB\BSON\UTCDateTime;
use yii\data\Pagination;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\HttpException;

use app\models\User;

use app\libs\Ui;

class UserController extends Controller{
	public function actionProfile(){
		if (!Yii::$app->user->can('app.user.profile'))
			Throw new HttpException(403);

		$identity = Yii::$app->user->getIdentity();
		if (Yii::$app->request->isPost) {
			$password = $_REQUEST['password'];
			$confirmPassword = $_REQUEST['confirmPassword'];
			$identity->setAttributes(Yii::$app->request->post('User'), false);
			$identity->createTime = new UTCDateTime();

			if(!empty($password)){
				$identity->generateAuthKey();
				$identity->setPassword($password);
			}
			if ($identity->save()) {
				Ui::setMessage('บันทึกข้อมูลสำเร็จ');
				Yii::info([
						'id' => (string)$identity->_id,
						], 'audit.user.profile');
			}else {
				Ui::setMessage('การบันทึกข้อมูลผิดพลาด','warning');
			}
		}
		return $this->render('profile',[
				'identity' => $identity
		]);
	}
	public function actionDelete($id) {
		if (!Yii::$app->user->can('app.user'))
			Throw new HttpException(403);
		$arrId = preg_split('/,/', $id, -1, PREG_SPLIT_NO_EMPTY);
		$ids = [];
		foreach($arrId as $key) {
			$ids[] = new ObjectID($key);
		}
		$query = User::find();
		$query->andWhere([
			'_id' => $ids,
		]);

		$deleted = 0;
		foreach($query->all() as $model) {
			$success = $model->delete();
				if ($success) $deleted++;
		}
		if ($deleted > 0) {
			Ui::setMessage("ลบข้อมูลจำนวน $deleted รายการ", 'success');
			Yii::info(json_encode([
					'userId' =>  \Yii::$app->user->id,
					'message' => "delete user ".json_encode($ids),
					]), 'audit.user.delete');
		}
		$this->redirect(['user/list']);
	}

	 public function actionEdit(){
	 	if (!Yii::$app->user->can('app.user'))
	 		Throw new HttpException(403);
	 	$currentModel = User::findOne(['_id' => Yii::$app->request->get('id')]);

		if (empty($currentModel)) $currentModel = new User();

		if (Yii::$app->request->isPost) {
			$password = $_REQUEST['password'];
			$confirmPassword = $_REQUEST['confirmPassword'];
			$currentModel->setAttributes(Yii::$app->request->post('User'), false);
			$currentModel->status = (int)Yii::$app->request->post('User')['status'];
			$currentModel->createTime = new UTCDateTime();
			$currentModel->generateAuthKey();
			if(!empty($password)){
				$currentModel->setPassword($password);
			}

			if ($currentModel->save()) {
				$auth = Yii::$app->authManager;
				$auth->revokeAll($currentModel->getId());
				$role = $auth->getRole($currentModel->role);
				if (!empty($role))
					$auth->assign($role, $currentModel->getId());

				Ui::setMessage('บันทึกข้อมูลสำเร็จ');
				Yii::info([
						'id' => (string)$currentModel->_id,
						], 'audit.user.save');
				return $this->redirect(Url::toRoute('user/list'));
			}else {
				Ui::setMessage('การบันทึกข้อมูลผิดพลาด','warning');
			}
		}

		return $this->render('edit', [
			'currentModel' => $currentModel,
		]);
	}
	public function actionList(){
		if (!Yii::$app->user->can('app.user'))
			Throw new HttpException(403);

		$query = $this->getQuery($_REQUEST);

		$pagination = new Pagination([
				'defaultPageSize' => Yii::$app->params['ui']['defaultPageSize'],
				'totalCount' => $query->count(),
				]);
		$lstMain = $query
		->orderBy('createTime')
		->offset($pagination->offset)
		->limit($pagination->limit)
		->all();
		return $this->render('list', [
			'lstMain' => $lstMain,
			'pagination' => $pagination,
		]);
	}
	private function getQuery($params) {
		$query = User::find();
		if (!empty($params['q']))
			$query->andWhere(['name' => new \MongoDB\BSON\Regex($params['q'])]);

		return $query;
	}
}

views/user/edit.php
<?php
use app\models\User;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Button;
use yii\helpers\Html;
use yii\helpers\Url;
use app\libs\Auth;

$baseUrl = \Yii::getAlias('@web');
$cancelUrl = Url::toRoute(['user/list']);
$str = <<<EOT
$('#btn-cancel').click(function() {
	location.assign('$cancelUrl');
});
$('#confirmPassword').on('keyup', function () {
	 if ($(this).val() == $('#password').val()) {
			$('#message').html('password ถูกต้อง').css('color', 'green');
    } else $('#message').html('password ไม่ถูกต้อง กรุณาลองอีกครั้งค่ะ').css('color', 'red');

});
EOT;
$this->registerJs($str);
?>
<?php $form = ActiveForm::begin([
				'layout' => 'horizontal',
		])
 ?>
 <div class="row">
      <div class="col-lg-12">
          <div class="widget-container fluid-height">
                <div class="heading tabs">
                   	 <i class="fa fa-user"></i>แก้ไขผู้ใช้
        		</div>
         <div class="tab-content padded" >
					<?= $form->field($currentModel, 'name')->textInput()?>

					<?= $form->field($currentModel, 'username')->textInput()?>

		   		<div class="form-group">
		       		 <label class="col-sm-3 control-label">Password</label>
		       			 <div class="col-sm-6">
		          		 	 <input type="password" class="form-control" name="password" id="password"/>
		       			 </div>
		   		</div>

	   		 <div class="form-group">
	       			 <label class="col-sm-3 control-label">Confirm Password</label>
	       				 <div class="col-sm-6">
	          				 <input type="password" class="form-control" name="confirmPassword"  id="confirmPassword"/>
	          				 <span id='message'>กรุณายืนยัน password </span>
	       				 </div>
	  		</div>

			<?= $form->field($currentModel, 'status')->dropDownList(
					User::$arrStatus
				)?>

				<?= $form->field($currentModel, 'role')->dropDownList(
					Auth::$arrUserRole
				)?>

        <div class="form-group">
			<div class="col-md-7 col-md-offset-3">
					<?= Button::widget([
					    'label' => 'บันทึก',
					    'options' => [
					    	'class' => 'btn-primary'
						],
					]);?>
					<?= Button::widget([
						'id' => 'btn-cancel',
					    'label' => 'ยกเลิก',
						'options' => [
							'type' => 'button',
						],
					]);?>
				</div>
             </div>
  		</div>
  	</div>
<?php ActiveForm::end() ?>

views/user/list.php
<?php
use app\models\User;

use jjoi\util\Date as DateUtil;
use yii\data\Pagination;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\LinkPager;

$deleteUrl =  Url::toRoute(['user/delete']);
$list = Url::toRoute(['user/list']);
$str = <<<EOT
	function postAction(action) {
		if(action == 'deleteList'){
			var obj = $('.main-content .widget-content tbody input[type=checkbox]:checked');
			var length = $('.main-content .widget-content tbody input[type=checkbox]:checked').length;
		if(length == 0){
			 	location.assign('$list');
		}else{
			var arrId = [];
			for(var i = 0; i<=obj.length; i++){
				arrId.push($(obj[i]).val());
				}
			$('#myModalAll').modal({show:true})
				$('.idDelAll').val(arrId);
				$('.modal-body #lengthId').text("ลบข้อมูลจำนวน  " + length + " รายการ");
				}
		}
	}

	$( ".idDelAll" ).on("click",function(){
		location.assign('$deleteUrl?id='+$(this).val());
});
	$( ".delete" ).on("click",function(){
		var id = $(this).data('id');
		var name = $(this).data('name');
		$('#myModal').modal({show:true})
		$('.idDel').val(id);

		$('.modal-body #nameId').text("ต้องการลบ " + name + " ใช่ไหมคะ");
});
	$( ".idDel" ).on("click",function(){
		location.assign('$deleteUrl?id='+$(this).val());
});
	$('.dropdown-menu a[data-action]').click(function() {
			postAction($(this).attr('data-action'));
});

EOT;
$this->registerJs($str);
?>
<style>
.modal-dialog {
	right: auto;
	left: 0%;
	width: 600px;
	padding-top: 30px;
	padding-bottom: 30px;
}
</style>
<div class="row">
	<div class="col-lg-12">
		<div class="widget-container fluid-height clearfix">
			<div class="heading">
				<i class="fa fa-user"></i>ผู้ใช้
				<i class="fa fa-cog pull-right" data-toggle=dropdown data-target="#dropdown"></i>
				<i class="fa fa-search pull-right" data-toggle="collapse" data-target="#search-form"></i>
				<a href="<?= Url::toRoute(['user/edit']) ?>"><i class="fa fa-plus pull-right" ></i></a>
			</div>
			<div class="widget-content">
				<div id="search-form" class="collapse" >
					<?php ActiveForm::begin(['class' => 'form-inline'])?>
	    	        	<div class="input-group col-sm-4 col-md-2 pull-right">
	                		<input class="form-control" type="text" name="q"><span class="input-group-btn"><button class="btn btn-default" type="submit" id="searchBtn">ค้นหา</button></span>
	              		</div>
		    	     <?php ActiveForm::end() ?>
	    	     </div>
	    	    <div id ="dropdown" class="dropdown">
  					<ul class="dropdown-menu pull-right" >
                          <li>
                            <a href="javascript:void(0);" data-action="deleteList">
                            <i class="fa fa-check-square-o"></i>ลบข้อมูล
                            </a>
                          </li>
 					 </ul>
	    	    </div>

				<table class="table table-striped">
					<thead>
						<th></th>
						<th>ชื่อ</th>
						<th>นามสกุล</th>
						<th>สถานะ</th>
						<th>เวลา</th>
						<th></th>
					</thead>
					<tbody>
<?php
	foreach($lstMain as $model) :
	?>
						<tr>
							<td class="checkboxes">
								<label><input name="ids[]" id="ids[]" type="checkbox"
								value="<?= $model->_id?>">
								<span></span>
								</label>
						</td>
							<td><a href = "<?= Url::toRoute(['user/edit', 'id' => (string)$model->_id]) ?>"> <?= $model->name ?> </a></td>
							<td><?= $model->username ?></td>
							<td><?= User::$arrStatus[$model->status]; ?></td>
							<td><?= (new DateUtil($model->createTime))->format('d-m-Y')?></td>
							<td class="actions">
								<div class="action-buttons">
									<a class="table-actions" href="<?= Url::toRoute(['user/edit', 'id' => (string)$model->_id]) ?>"><i class="fa fa-pencil"></i></a>
									<a class="table-actions delete" data-id=<?= (string)$model->_id ?> data-name="<?= $model->name ?>"><i class="fa fa-trash-o "></i></a>
								</div>
							</td>
						</tr>
		<div class="modal fade" id="myModal"
		tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  			<div class="modal-dialog">
  			  <div class="modal-content">
    			  <div class="modal-header">
     				   <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      				   <h4 class="modal-title" id="myModalLabel">ยืนยันการลบ</h4>
     			 </div>
      			<div class="modal-body">
      				<div id="nameId"></div>
    		  	</div>
     			 <div class="modal-footer">
     			 		  <button type="button" class="btn btn-default" data-dismiss="modal">ยกเลิก</button>
         				  <button type="button" class="btn btn-primary idDel">ลบ</button>
    			</div>
   		</div>
 	 </div>
</div>
<div class="modal fade" id="myModalAll"
		tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  			<div class="modal-dialog">
  			  <div class="modal-content">
    			  <div class="modal-header">
     				   <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      				   <h4 class="modal-title" id="myModalLabel">ต้องการลบใช่ไหม</h4>
     			 </div>
     			 <div class="modal-body">
      					<div id="lengthId"></div>
    		  	</div>
     			 <div class="modal-footer">
     			 		  <button type="button" class="btn btn-default" data-dismiss="modal">ยกเลิก</button>
         				  <button type="button" class="btn btn-primary idDelAll">ลบ</button>
    			  </div>
   			 </div>
 		 </div>
</div>
<?php
	endforeach;
	?>
					</tbody>
				</table>
				<?php echo LinkPager::widget(['pagination' => $pagination, 'options' => ['class'=> 'pagination pull-right']])?>
			</div>
		</div>
	</div>
</div>

views/user/profile.php
<?php
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Button;
use yii\helpers\Html;
use yii\helpers\Url;

use app\models\User;

$baseUrl = \Yii::getAlias('@web');
$cancelUrl = Url::toRoute(['/site']);
$str = <<<EOT
$('#btn-cancel').click(function() {
	location.assign('$cancelUrl');
});
$('#confirmPassword').on('keyup', function () {
	 if ($(this).val() == $('#password').val()) {
			$('#message').html('password ถูกต้อง').css('color', 'green');
    } else $('#message').html('password ไม่ถูกต้อง กรุณาลองอีกครั้งค่ะ').css('color', 'red');
		
});
EOT;
$this->registerJs($str);
?>
<?php $form = ActiveForm::begin([
				'layout' => 'horizontal',
		])
?>	
<div class="row">
	<div class="col-lg-12">
		<div class="widget-container fluid-height">
			<div class="heading tabs">
				<i class="fa fa-user"></i>แก้ไขผู้ใช้
			</div>
			<div class="tab-content padded">
				<?= $form->field($identity, 'name')->textInput()?>
				
				<?= $form->field($identity, 'username')->textInput([
						'class' => 'form-control fieldset ',
						'disabled' => 'true'
				])?>
				
				<div class="form-group">
					<label class="col-sm-3 control-label">Password</label>
					<div class="col-sm-6">
						<input type="password" class="form-control" name="password" id="password"/>
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label">Confirm Password</label>
					<div class="col-sm-6">
						<input type="password" class="form-control" name="confirmPassword"  id="confirmPassword"/>
						<span id='message'>กรุณายืนยัน password </span>
					</div>
				</div>
						
				<div class="form-group">
					<div class="col-md-7 col-md-offset-3">
							<?= Button::widget([
								'label' => 'บันทึก',
								'options' => [
									'class' => 'btn btn-primary'
								],
							]);?>
							<?= Button::widget([
								'id' => 'btn btn-cancel',
								'label' => 'ยกเลิก',
								'options' => [
									'type' => 'button',
								],
							]);?>
					</div>
				</div>
			</div>
		</div>
<?php ActiveForm::end() ?>